import type { IntakeSession } from "@/lib/intake/types";

export const FIXTURE_NOW = Date.parse("2026-08-15T10:42:00Z");

function secondsAgo(seconds: number) {
  return FIXTURE_NOW - seconds * 1000;
}

export const FIXTURE_SESSIONS: IntakeSession[] = [
  {
    id: "ada7k2mq",
    values: {
      firstName: "Ada",
      middleName: "Kwabena",
      lastName: "Mensah",
      dateOfBirth: "1991-03-12",
      gender: "Female",
      phone: "+1 415 555 0148",
      email: "ada.mensah@",
      address: "418 Marina Blvd, San Francisco, CA 94123",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(320),
      middleName: secondsAgo(310),
      lastName: secondsAgo(300),
      dateOfBirth: secondsAgo(280),
      gender: secondsAgo(260),
      phone: secondsAgo(120),
      address: secondsAgo(40),
      email: secondsAgo(8),
    },
    lastKeystrokeAt: secondsAgo(8),
    submittedAt: null,
    failedValidations: {},
    errorSubmits: 0,
  },
  {
    id: "ravi93xd",
    values: {
      firstName: "Ravi",
      lastName: "Kulkarni",
      dateOfBirth: "1978-09-02",
      gender: "Male",
      phone: "+1 415 555 0102",
      email: "r.kulkarni@mail.com",
      address: "22 Bayview St, San Francisco, CA 94124",
      preferredLanguage: "English",
      nationality: "Indian",
      emergencyContactName: "Priya Kulkarni",
      emergencyContactRelationship: "Spouse or partner",
      emergencyContactPhone: "+1 415 555 0177",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(900),
      lastName: secondsAgo(880),
      dateOfBirth: secondsAgo(860),
      gender: secondsAgo(840),
      phone: secondsAgo(700),
      email: secondsAgo(660),
      address: secondsAgo(600),
      preferredLanguage: secondsAgo(500),
      nationality: secondsAgo(480),
      emergencyContactName: secondsAgo(300),
      emergencyContactRelationship: secondsAgo(280),
      emergencyContactPhone: secondsAgo(260),
    },
    lastKeystrokeAt: secondsAgo(260),
    submittedAt: secondsAgo(240),
    failedValidations: {},
    errorSubmits: 0,
  },
  {
    id: "noor4tzp",
    values: {
      firstName: "Noor",
      lastName: "Haddad",
      dateOfBirth: "1994-04-27",
      gender: "Female",
      phone: "+1 415 55",
      email: "noor.haddad@mail.com",
      address: "1180 Sutter St, San Francisco, CA 94109",
      preferredLanguage: "Arabic",
      nationality: "American",
      religion: "Muslim",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(420),
      lastName: secondsAgo(410),
      dateOfBirth: secondsAgo(400),
      gender: secondsAgo(390),
      email: secondsAgo(300),
      address: secondsAgo(240),
      preferredLanguage: secondsAgo(180),
      nationality: secondsAgo(160),
      religion: secondsAgo(140),
      phone: secondsAgo(45),
    },
    lastKeystrokeAt: secondsAgo(45),
    submittedAt: null,
    failedValidations: { phone: 3 },
    errorSubmits: 1,
  },
  {
    id: "jonas6vh",
    values: {
      firstName: "Jonas",
      lastName: "Weber",
      dateOfBirth: "2001-07-18",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(30),
      lastName: secondsAgo(14),
      dateOfBirth: secondsAgo(4),
    },
    lastKeystrokeAt: secondsAgo(4),
    submittedAt: null,
    failedValidations: {},
    errorSubmits: 0,
  },
  {
    id: "marta5wq",
    values: {
      firstName: "Marta",
      lastName: "Oliveira",
      dateOfBirth: "1965-01-30",
      gender: "Prefer not to say",
      address: "77 Dolores St, San Francisco, CA 94103",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(900),
      lastName: secondsAgo(880),
      dateOfBirth: secondsAgo(800),
      gender: secondsAgo(700),
      address: secondsAgo(360),
    },
    lastKeystrokeAt: secondsAgo(360),
    submittedAt: null,
    failedValidations: { phone: 4 },
    errorSubmits: 2,
  },
  {
    id: "lucia8bn",
    values: {
      firstName: "Lucia",
      lastName: "Ferrari",
      dateOfBirth: "1988-12-05",
      gender: "Female",
      phone: "+1 415 555 0190",
      email: "l.ferrari@mail.com",
      address: "310 Union St, San Francisco, CA 94133",
      preferredLanguage: "English",
      nationality: "Italian",
    },
    fieldUpdatedAt: {
      firstName: secondsAgo(1_600),
      lastName: secondsAgo(1_580),
      dateOfBirth: secondsAgo(1_560),
      gender: secondsAgo(1_540),
      phone: secondsAgo(1_400),
      email: secondsAgo(1_380),
      address: secondsAgo(1_320),
      preferredLanguage: secondsAgo(1_290),
      nationality: secondsAgo(1_270),
    },
    lastKeystrokeAt: secondsAgo(1_270),
    submittedAt: secondsAgo(1_260),
    failedValidations: {},
    errorSubmits: 0,
  },
  {
    id: "newx3rj9",
    values: {},
    fieldUpdatedAt: {},
    lastKeystrokeAt: secondsAgo(12),
    submittedAt: null,
    failedValidations: {},
    errorSubmits: 0,
  },
];
