import type { FieldDef, FieldId, StepId } from "./types";

export const STEPS: {
  id: StepId;
  title: string;
  question: string;
  intro: string;
}[] = [
  {
    id: 1,
    title: "About you",
    question: "Let's start with your name",
    intro: "Exactly as it appears on your ID.",
  },
  {
    id: 2,
    title: "Contact",
    question: "How can we reach you?",
    intro: "We use this to confirm your appointment and send results.",
  },
  {
    id: 3,
    title: "Preferences",
    question: "A few preferences",
    intro: "So we can book an interpreter if you need one.",
  },
  {
    id: 4,
    title: "Emergency",
    question: "Anything else we should know?",
    intro: "Nothing here is required. Leave it blank and continue.",
  },
];

export const GENDER_OPTIONS = ["Female", "Male", "Prefer not to say"];

export const LANGUAGE_OPTIONS = [
  "English",
  "Spanish",
  "Mandarin",
  "French",
  "Thai",
];

export const NATIONALITY_OPTIONS = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Citizen of Antigua and Barbuda",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Citizen of Bosnia and Herzegovina",
  "Botswanan",
  "Brazilian",
  "British",
  "British Virgin Islander",
  "Bruneian",
  "Bulgarian",
  "Burkinan",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Cayman Islander",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese (Congo)",
  "Congolese (DRC)",
  "Cook Islander",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cymraes",
  "Cymro",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Citizen of the Dominican Republic",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "English",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Greenlandic",
  "Grenadian",
  "Guamanian",
  "Guatemalan",
  "Citizen of Guinea-Bissau",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kittitian",
  "Citizen of Kiribati",
  "Kosovan",
  "Kuwaiti",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtenstein citizen",
  "Lithuanian",
  "Luxembourger",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Martiniquais",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mosotho",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niuean",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Pitcairn Islander",
  "Polish",
  "Portuguese",
  "Prydeinig",
  "Puerto Rican",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Salvadorean",
  "Sammarinese",
  "Samoan",
  "Sao Tomean",
  "Saudi Arabian",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Citizen of Seychelles",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "St Helenian",
  "St Lucian",
  "Stateless",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian",
  "Tristanian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vatican citizen",
  "Citizen of Vanuatu",
  "Venezuelan",
  "Vietnamese",
  "Vincentian",
  "Wallisian",
  "Welsh",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];

export const RELATIONSHIP_OPTIONS = [
  "Parent",
  "Sibling",
  "Spouse or partner",
  "Child",
  "Friend",
  "Other",
];

export const RELIGION_OPTIONS = [
  "Prefer not to say",
  "Buddhist",
  "Christian",
  "Hindu",
  "Jewish",
  "Muslim",
  "None",
  "Other",
];

export const FIELDS: FieldDef[] = [
  {
    id: "firstName",
    label: "First name",
    step: 1,
    kind: "text",
    required: true,
  },
  {
    id: "middleName",
    label: "Middle name",
    step: 1,
    kind: "text",
    required: false,
    help: "Add if you have one.",
  },
  { id: "lastName", label: "Last name", step: 1, kind: "text", required: true },
  {
    id: "dateOfBirth",
    label: "Date of birth",
    step: 1,
    kind: "date",
    required: true,
  },
  {
    id: "gender",
    label: "Gender",
    step: 1,
    kind: "radio",
    required: true,
    options: GENDER_OPTIONS,
  },
  { id: "phone", label: "Phone number", step: 2, kind: "tel", required: true },
  {
    id: "email",
    label: "Email",
    step: 2,
    kind: "email",
    required: true,
    help: "We only email about your care.",
  },
  {
    id: "address",
    label: "Home address",
    step: 2,
    kind: "textarea",
    required: true,
  },
  {
    id: "preferredLanguage",
    label: "Preferred language",
    step: 3,
    kind: "combobox",
    required: true,
    options: LANGUAGE_OPTIONS,
  },
  {
    id: "nationality",
    label: "Nationality",
    step: 3,
    kind: "combobox",
    required: true,
    options: NATIONALITY_OPTIONS,
  },
  {
    id: "religion",
    label: "Religion",
    step: 3,
    kind: "combobox",
    required: true,
    options: RELIGION_OPTIONS,
  },
  {
    id: "emergencyContactName",
    label: "Emergency contact",
    step: 4,
    kind: "text",
    required: false,
    help: "Filling one of these three asks for the other two.",
  },
  {
    id: "emergencyContactRelationship",
    label: "Relationship",
    step: 4,
    kind: "select",
    required: false,
    options: RELATIONSHIP_OPTIONS,
  },
  {
    id: "emergencyContactPhone",
    label: "Emergency Contact Phone",
    step: 4,
    kind: "tel",
    required: false,
  },
];

export const TOTAL_FIELDS = FIELDS.length;

export const OPTIONAL_FIELD_IDS = FIELDS.filter((f) => !f.required).map(
  (f) => f.id,
);

export function getField(id: FieldId): FieldDef {
  const field = FIELDS.find((f) => f.id === id);
  if (!field) throw new Error(`Unknown field: ${id}`);
  return field;
}

export function fieldsForStep(step: StepId): FieldDef[] {
  return FIELDS.filter((f) => f.step === step);
}
